[tool.basedpyright]
typeCheckingMode = "standard"
reportMissingSuperCall = false
reportPrivateImportUsage = false
reportOptionalSubscript = false
reportOperatorIssue = false
reportOptionalMemberAccess = false
